print('hello, i am shreyansh tyagi from ghazaibad\nmy email address is shreytyagi3221@gmail.com\nmy nickname is sunny tyagi\nstudying from geeksforgeeks\n\n')
print('hello','i am shreyansh tyagi from ghaziabad',sep=',',end='\n')
print('my email address is shreytyagi3221','gmail.com',sep='@',end='\n')
print('my nickname is sunny tyagi',sep='',end='\n')
print('i am studying from','geeks',sep=' ',end='')
print('forgeeks',sep='#',end='\n')
print('dob','02','09','1999',sep='-',end='\n')